<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260417060302 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, inventory VARCHAR(255) NOT NULL, serial VARCHAR(255) NOT NULL, equipment_attributes JSON DEFAULT NULL, raion_id INT DEFAULT NULL, equipment_type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D338D583D0F62CC9 ON equipment (raion_id)');
        $this->addSql('CREATE INDEX IDX_D338D583B337437C ON equipment (equipment_type_id)');
        $this->addSql('CREATE TABLE equipment_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, label VARCHAR(255) NOT NULL, data_type VARCHAR(50) NOT NULL, is_multiple BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE equipment_attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, sort VARCHAR(255) DEFAULT 0 NOT NULL, equipment_attribute_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D7A5F46138DD965 ON equipment_attribute_option (equipment_attribute_id)');
        $this->addSql('CREATE TABLE equipment_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE equipment_type_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, required BOOLEAN DEFAULT false NOT NULL, sort INT DEFAULT 0 NOT NULL, equipment_type_id INT DEFAULT NULL, equipment_attribute_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9BBCFAEAB337437C ON equipment_type_attribute (equipment_type_id)');
        $this->addSql('CREATE INDEX IDX_9BBCFAEA138DD965 ON equipment_type_attribute (equipment_attribute_id)');
        $this->addSql('CREATE TABLE raion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(6) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, json JSON NOT NULL, raion_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649D0F62CC9 ON "user" (raion_id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583D0F62CC9 FOREIGN KEY (raion_id) REFERENCES raion (id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583B337437C FOREIGN KEY (equipment_type_id) REFERENCES equipment_type (id)');
        $this->addSql('ALTER TABLE equipment_attribute_option ADD CONSTRAINT FK_D7A5F46138DD965 FOREIGN KEY (equipment_attribute_id) REFERENCES equipment_attribute (id)');
        $this->addSql('ALTER TABLE equipment_type_attribute ADD CONSTRAINT FK_9BBCFAEAB337437C FOREIGN KEY (equipment_type_id) REFERENCES equipment_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE equipment_type_attribute ADD CONSTRAINT FK_9BBCFAEA138DD965 FOREIGN KEY (equipment_attribute_id) REFERENCES equipment_attribute (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649D0F62CC9 FOREIGN KEY (raion_id) REFERENCES raion (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583D0F62CC9');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583B337437C');
        $this->addSql('ALTER TABLE equipment_attribute_option DROP CONSTRAINT FK_D7A5F46138DD965');
        $this->addSql('ALTER TABLE equipment_type_attribute DROP CONSTRAINT FK_9BBCFAEAB337437C');
        $this->addSql('ALTER TABLE equipment_type_attribute DROP CONSTRAINT FK_9BBCFAEA138DD965');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649D0F62CC9');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE equipment_attribute');
        $this->addSql('DROP TABLE equipment_attribute_option');
        $this->addSql('DROP TABLE equipment_type');
        $this->addSql('DROP TABLE equipment_type_attribute');
        $this->addSql('DROP TABLE raion');
        $this->addSql('DROP TABLE "user"');
    }
}
