<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405083421 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE type_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, required BOOLEAN DEFAULT NULL, sort_order INT DEFAULT NULL, type_id INT NOT NULL, attribute_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4EBCAEEBC54C8C93 ON type_attribute (type_id)');
        $this->addSql('CREATE INDEX IDX_4EBCAEEBB6E62EFA ON type_attribute (attribute_id)');
        $this->addSql('ALTER TABLE type_attribute ADD CONSTRAINT FK_4EBCAEEBC54C8C93 FOREIGN KEY (type_id) REFERENCES equipment_type (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE type_attribute ADD CONSTRAINT FK_4EBCAEEBB6E62EFA FOREIGN KEY (attribute_id) REFERENCES equipment_attribute (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE type_attribute DROP CONSTRAINT FK_4EBCAEEBC54C8C93');
        $this->addSql('ALTER TABLE type_attribute DROP CONSTRAINT FK_4EBCAEEBB6E62EFA');
        $this->addSql('DROP TABLE type_attribute');
    }
}
