<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260411161832 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE equipment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, inventory VARCHAR(255) NOT NULL, serial VARCHAR(255) NOT NULL, attributes JSONB DEFAULT NULL, raion_id INT DEFAULT NULL, type_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D338D583D0F62CC9 ON equipment (raion_id)');
        $this->addSql('CREATE INDEX IDX_D338D583C54C8C93 ON equipment (type_id)');
        $this->addSql('CREATE TABLE equipment_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, label VARCHAR(255) NOT NULL, data_type VARCHAR(50) NOT NULL, is_multiple BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE equipment_attribute_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, value VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, sort VARCHAR(255) DEFAULT 0 NOT NULL, attribute_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D7A5F46B6E62EFA ON equipment_attribute_option (attribute_id)');
        $this->addSql('CREATE TABLE equipment_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE equipment_type_attribute (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, required BOOLEAN DEFAULT false NOT NULL, sort INT DEFAULT 0 NOT NULL, type_id INT DEFAULT NULL, attribute_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9BBCFAEAC54C8C93 ON equipment_type_attribute (type_id)');
        $this->addSql('CREATE INDEX IDX_9BBCFAEAB6E62EFA ON equipment_type_attribute (attribute_id)');
        $this->addSql('CREATE TABLE raion (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, code VARCHAR(6) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, json JSON NOT NULL, raion_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D649D0F62CC9 ON "user" (raion_id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583D0F62CC9 FOREIGN KEY (raion_id) REFERENCES raion (id)');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583C54C8C93 FOREIGN KEY (type_id) REFERENCES equipment_type (id)');
        $this->addSql('ALTER TABLE equipment_attribute_option ADD CONSTRAINT FK_D7A5F46B6E62EFA FOREIGN KEY (attribute_id) REFERENCES equipment_attribute (id)');
        $this->addSql('ALTER TABLE equipment_type_attribute ADD CONSTRAINT FK_9BBCFAEAC54C8C93 FOREIGN KEY (type_id) REFERENCES equipment_type (id)');
        $this->addSql('ALTER TABLE equipment_type_attribute ADD CONSTRAINT FK_9BBCFAEAB6E62EFA FOREIGN KEY (attribute_id) REFERENCES equipment_attribute (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649D0F62CC9 FOREIGN KEY (raion_id) REFERENCES raion (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583D0F62CC9');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583C54C8C93');
        $this->addSql('ALTER TABLE equipment_attribute_option DROP CONSTRAINT FK_D7A5F46B6E62EFA');
        $this->addSql('ALTER TABLE equipment_type_attribute DROP CONSTRAINT FK_9BBCFAEAC54C8C93');
        $this->addSql('ALTER TABLE equipment_type_attribute DROP CONSTRAINT FK_9BBCFAEAB6E62EFA');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649D0F62CC9');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE equipment_attribute');
        $this->addSql('DROP TABLE equipment_attribute_option');
        $this->addSql('DROP TABLE equipment_type');
        $this->addSql('DROP TABLE equipment_type_attribute');
        $this->addSql('DROP TABLE raion');
        $this->addSql('DROP TABLE "user"');
    }
}
